import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'zlb' at '17-2-21 下午10:46' with Gradle 2.14.1
 *
 * @author zlb, @date 17-2-21 下午10:46
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
       
    }
}
